// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storety.Data;

#nullable disable

namespace Storety.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Storety.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 0,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 0,
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 0,
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 0,
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 0,
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 0,
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 0,
                            Name = "Category 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
